# Generated by Django 4.2.1 on 2023-05-28 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=5, unique=True)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.shipment')),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='cars',
            field=models.ManyToManyField(through='car.ShipmentCar', to='car.car'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_shipments', to='car.location'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pick_up',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_up_shipments', to='car.location'),
        ),
        migrations.AddField(
            model_name='car',
            name='current_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.location'),
        ),
    ]
